export const NEWS_QUOTES = [
  "The press is a powerful weapon. I intend to wield it.",
  "Get me that story! Headlines sell papers, and I want this on the front page!",
  "Journalism is about uncovering the truth!",
  "No story is too small if it's the truth.",
  "We need facts, not fluff!",
  "This is a newspaper, not a knitting circle.",
  "Seems we've got a bit of news. Just listen to this.",
  "And here's me! With the news.",
  "We interrupt our regularly scheduled program for some news!",
  "Here's some news from the world outside.",
  "Let's hear... about the world.",
  "Stay tuned, America, for updates!",
  "And now, a super important public service announcement.",
  "Bringing you the truth, no matter how bad it hurts.",
];

export const TAGS = [
  "bitcoin",
  "nostr",
  "lightning",
  "programming",
  "hiring",
  "ai",
  "tech",
  "science",
  "politics",
  "sports",
  "entertainment",
  "business",
  "finance",
  "health",
  "weather",
  "philosophy",
  "religion",
  "art",
  "music",
  "culture",
  "history",
  "education",
  "travel",
  "food",
];
